import Footer from "./component/footer";
import Header from "./component/Header";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex justify-center items-center h-screen">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
